name: react deployyyy
on:
  push:
    branches:
      - main

jobs:
  My-deploy-Job:
    runs-on: ubuntu-latest
    env:
      REMOTE_DIR: /home/ubuntu/2025action

    steps:
      - name: ssh to ec2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ${{ env.REMOTE_DIR }}
            pwd
